export const rawSnapshot = {
  api_version: 'v1',
  server_time_ms: 1_800_000,
  from_ms: 0,
  to_ms: 1_800_000,
  target_range: { low_mg_dl: 75.6, high_mg_dl: 162, low_mmol_l: 4.2, high_mmol_l: 9 },
  current_glucose: {
    reading_id: 'current',
    measured_at_ms: 1_500_000,
    glucose_mg_dl: 108,
    trend_mg_dl_min: -0.5,
    sensor_id: 'sensor',
    sensor_generation: '3',
    quality: 0.95,
    utc_offset_minutes: 180,
    received_at_ms: 1_501_000,
    age_ms: 300_000,
    is_stale: false,
  },
  glucose_history: [
    {
      reading_id: 'new',
      measured_at_ms: 1_500_000,
      glucose_mg_dl: 108,
      trend_mg_dl_min: -0.5,
      sensor_id: null,
      sensor_generation: null,
      quality: 0.95,
      utc_offset_minutes: 180,
      received_at_ms: 1_501_000,
    },
    {
      reading_id: 'old',
      measured_at_ms: 600_000,
      glucose_mg_dl: 126,
      trend_mg_dl_min: 0.2,
      sensor_id: null,
      sensor_generation: null,
      quality: null,
      utc_offset_minutes: 180,
      received_at_ms: 601_000,
    },
  ],
  glucose_history_order: 'oldest_first',
  glucose_history_truncated: false,
  intake_events: [
    {
      id: 'meal-1',
      kind: 'meal',
      occurred_at_ms: 900_000,
      meal_text: 'Рис',
      carbs_g: 42,
      portion_g: 180,
      insulin_units: null,
      insulin_type: null,
      insulin_name: null,
      updated_at_ms: 910_000,
    },
    {
      id: 'rapid-1',
      kind: 'rapid',
      occurred_at_ms: 1_200_000,
      meal_text: null,
      carbs_g: null,
      portion_g: null,
      insulin_units: 5,
      insulin_type: 'rapid',
      insulin_name: 'NovoRapid',
      updated_at_ms: 1_201_000,
    },
  ],
  intake_events_order: 'oldest_first',
  intake_events_truncated: false,
  insulin_events: [
    {
      occurred_at_ms: 750_000,
      insulin_units: 12,
      insulin_type: 'long',
      insulin_name: 'Tresiba',
    },
    {
      occurred_at_ms: 1_200_000,
      insulin_units: 5,
      insulin_type: 'rapid',
      insulin_name: 'NovoRapid',
    },
  ],
  forecast: {
    status: 'ready',
    generated_at_ms: 1_800_000,
    based_on_reading_at_ms: 1_500_000,
    based_on_glucose_mg_dl: 108,
    horizon_minutes: 120,
    model_version: 'test-v1',
    confidence: 0.76,
    points: [
      { at_ms: 2_400_000, median_mg_dl: 101, low_mg_dl: 80, high_mg_dl: 130 },
      { at_ms: 2_100_000, median_mg_dl: 105, low_mg_dl: 88, high_mg_dl: 124 },
    ],
    activities: [],
    conditional_notice: 'Forecast only.',
  },
}
